### PR TITLE
Squash and Reconcile from fork, 1.21.3 also

### PR DESCRIPTION
**Pull request by sakura-ryoko**
- Various code cleanups & better i18n support with some optional Crowdin files that can be added.
- Fixes / replaces basic "modid.png" with logo from Modrinth, and corrects ModMenu display integration.
- Moves Configs and Hotkeys / Keybind callbacks to their own classes with new `.apply()` method for MaLiLib configs.
- Fixes 'Logging / Debugging' system with a proper logger, and related `printDebug` config.
- Uses Jitpack for 1.21.3 builds for Litematica / MaLiLib based on my repos.

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
Working on more Crowdin items across the mod ecosystem

**Comment by sakura-ryoko** [comment]
Obviously I might want to remove the jitpack and crowdin yml files...

**Comment by aleksilassila** [comment]
Very nice, thank you! Is this ready to merge?

**Comment by sakura-ryoko** [comment]
All done with that.

**Comment by sakura-ryoko** [comment]
👍

**Pull request merged**
